/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/property/address-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAddressHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/property/directory-fields/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PatchDirectoryField"];
        trace?: never;
    };
    "/api/v1/property/directory-fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDirectoryFields"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/property/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["PatchOwner"];
        trace?: never;
    };
    "/api/v1/property": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetProperty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDrafts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StripeWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetStatement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/unpaid-assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetUnpaidAssessments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/recurring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetRecurring"];
        put: operations["UpsertRecurring"];
        post?: never;
        delete: operations["CancelRecurring"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/recurring/setup-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateSetupIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/one-time/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ConfirmOneTimePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreatePaymentIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPaymentOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/receipts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPaymentTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/jobs/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReconcilePayments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/jobs/run-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RunRecurringDrafts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/alert-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAlertPreferences"];
        put: operations["UpdateAlertPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IngestBrowserTelemetry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/violations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetViolations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPoll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/poll/{id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["VotePoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/events/{id}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RsvpEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/documents/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDocumentDownload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetCommunityDirectory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/announcements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAnnouncement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAnnouncements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RefreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/switch-property": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SwitchProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddressHistoryDto: {
            /** Format: guid */
            id: string;
            eventType: string;
            address: string;
            /** Format: date */
            effectiveDate: string;
        };
        DirectoryFieldDto: {
            /** Format: guid */
            id: string;
            fieldKey: string;
            label: string;
            shared: boolean;
        };
        DirectoryFieldPatchRequest2: {
            shared: boolean;
        };
        OwnerDto: {
            /** Format: guid */
            id: string;
            firstName: string;
            lastName: string;
            ownerName2?: string | null;
            email: string;
            phone?: string | null;
            mailingToProperty: boolean;
            mailingAddress?: string | null;
            paperlessStatements: boolean;
            smsReminders: boolean;
            votingRights: boolean;
            accountNumber: string;
            communityName: string;
            propertyAddress: string;
            memberSince?: string | null;
        };
        OwnerPatchRequest: {
            firstName?: string | null;
            lastName?: string | null;
            ownerName2?: string | null;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            mailingToProperty?: boolean | null;
            mailingAddress?: string | null;
            paperlessStatements?: boolean | null;
            smsReminders?: boolean | null;
        };
        ErrorResponse: {
            /**
             * Format: int32
             * @default 400
             */
            statusCode: number;
            /** @default One or more errors occurred! */
            message: string;
            errors: {
                [key: string]: string[];
            };
        };
        PropertyDto: {
            /** Format: guid */
            id: string;
            accountNumber: string;
            communityId: string;
            communityName: string;
            address: string;
            city: string;
            state: string;
            zip: string;
            lot: string;
            phase?: string | null;
            section: string;
            block?: string | null;
            /** Format: int32 */
            fiscalYear: number;
            /** Format: int32 */
            yearBuilt: number;
            status: string;
            /** Format: decimal */
            monthlyAssessment: number;
            /** Format: decimal */
            annualAssessment: number;
            /** Format: int32 */
            assessmentDueDay: number;
            /** Format: decimal */
            lateFeeAmount: number;
            /** Format: int32 */
            lateFeeGraceDays: number;
            /** Format: decimal */
            financeChargeRate: number;
        };
        DraftsResponse: {
            items: components["schemas"]["DraftEntryDto"][];
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
        };
        DraftEntryDto: {
            /** Format: guid */
            id: string;
            /** Format: date */
            draftDate: string;
            sourceLabel: string;
            /** Format: decimal */
            amount: number;
            status: string;
            transactionStatus?: string | null;
        };
        DraftsRequest: Record<string, never>;
        LedgerResponse: {
            items: components["schemas"]["LedgerItemDto"][];
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalPages: number;
        };
        LedgerItemDto: {
            /** Format: guid */
            id: string;
            /** Format: date */
            entryDate: string;
            documentNumber?: string | null;
            description: string;
            /** Format: decimal */
            chargeAmount: number;
            /** Format: decimal */
            paymentAmount: number;
            /** Format: decimal */
            runningBalance: number;
            entryType: string;
        };
        LedgerRequest: Record<string, never>;
        StatementResponse: {
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: decimal */
            openingBalance: number;
            /** Format: decimal */
            totalCharges: number;
            /** Format: decimal */
            totalPayments: number;
            /** Format: decimal */
            closingBalance: number;
            lines: components["schemas"]["StatementLineDto"][];
        };
        StatementLineDto: {
            /** Format: date */
            entryDate: string;
            documentNumber?: string | null;
            description: string;
            /** Format: decimal */
            chargeAmount: number;
            /** Format: decimal */
            paymentAmount: number;
            /** Format: decimal */
            runningBalance: number;
            entryType: string;
        };
        StatementRequest: Record<string, never>;
        UnpaidAssessmentsResponse: {
            /** Format: date */
            asOf: string;
            /** Format: decimal */
            totalDue: number;
            /** Format: decimal */
            creditBalance: number;
            breakdown: components["schemas"]["UnpaidAssessmentLineDto"][];
        };
        UnpaidAssessmentLineDto: {
            category: string;
            /** Format: decimal */
            amount: number;
        };
        RecurringPaymentDto: {
            /** Format: guid */
            id: string;
            amountType: string;
            /** Format: decimal */
            fixedAmount?: number | null;
            method: string;
            /** Format: int32 */
            draftDay: number;
            status: string;
            /** Format: decimal */
            processingFee: number;
            maskedMethod?: string | null;
            /** Format: date */
            nextDraftDate?: string | null;
            /** Format: decimal */
            nextDraftAmount?: number | null;
            /** Format: date-time */
            mandateAcceptedAt?: string | null;
        };
        RecurringPaymentRequest: {
            amountType: string;
            /** Format: decimal */
            fixedAmount?: number | null;
            /** Format: int32 */
            draftDay: number;
            setupIntentId: string;
            mandateAccepted: boolean;
            mandateText?: string | null;
            mandateVersion?: string | null;
        };
        SetupIntentResponse: {
            setupIntentId: string;
            clientSecret: string;
            publishableKey: string;
        };
        ConfirmPaymentResponse: {
            /** Format: guid */
            transactionId: string;
            status: string;
            /** Format: decimal */
            grossAmount: number;
            /** Format: decimal */
            feeAmount: number;
            /** Format: decimal */
            total: number;
            maskedMethod: string;
            confirmationNumber?: string | null;
            /** Format: guid */
            receiptId?: string | null;
        };
        ConfirmPaymentRequest: {
            paymentIntentId: string;
        };
        CreateIntentResponse: {
            paymentIntentId: string;
            clientSecret: string;
            /** Format: decimal */
            amount: number;
            /** Format: decimal */
            fee: number;
            /** Format: decimal */
            total: number;
        };
        CreateIntentRequest: {
            /** Format: decimal */
            amount: number;
            method: string;
        };
        PaymentOptionsResponse: {
            /** Format: decimal */
            currentBalance: number;
            /** Format: decimal */
            creditBalance: number;
            /** Format: decimal */
            nextAssessment: number;
            /** Format: date */
            nextAssessmentDueDate?: string | null;
            cardFeeType: string;
            /** Format: decimal */
            cardFeeValue: number;
            cardScope: string;
            surchargingEnabled: boolean;
            /** Format: decimal */
            achFeeValue: number;
        };
        ReceiptResponse: {
            /** Format: guid */
            id: string;
            /** Format: guid */
            transactionId: string;
            confirmationNumber: string;
            maskedMethod: string;
            /** Format: decimal */
            grossAmount: number;
            /** Format: decimal */
            feeAmount: number;
            /** Format: decimal */
            total: number;
            /** Format: date-time */
            issuedAt: string;
        };
        TransactionsResponse: {
            items: components["schemas"]["TransactionDto"][];
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
        };
        TransactionDto: {
            /** Format: guid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: decimal */
            grossAmount: number;
            /** Format: decimal */
            feeAmount: number;
            /** Format: decimal */
            total: number;
            /** Format: decimal */
            cumulativeRefundedAmount: number;
            status: string;
            paymentMethod: string;
            maskedMethod: string;
            isRecurring: boolean;
        };
        ReconcileResponse: {
            /** Format: int32 */
            resolvedAchTransactions: number;
            /** Format: int32 */
            retriedWebhooks: number;
            /** Format: int32 */
            dispatchedAlerts: number;
            /** Format: int32 */
            ledgerInconsistencies: number;
        };
        RunDraftsResponse: {
            /** Format: int32 */
            dueCount: number;
            /** Format: int32 */
            charged: number;
            /** Format: int32 */
            failed: number;
            /** Format: int32 */
            skipped: number;
            /** Format: int32 */
            noticesSent: number;
        };
        AlertPreferencesDto: {
            smsOptIn: boolean;
            emailOptIn: boolean;
            alertPhone?: string | null;
        };
        UpdateAlertPreferencesRequest: {
            smsOptIn: boolean;
            emailOptIn: boolean;
            alertPhone?: string | null;
        };
        DashboardResponse: {
            /** Format: decimal */
            currentBalance: number;
            balanceDueDate: string;
            /** Format: int32 */
            openViolations: number;
            /** Format: int32 */
            documentCount: number;
            /** Format: int32 */
            newDocumentsThisMonth: number;
            pinnedAnnouncement?: components["schemas"]["AnnouncementSummary"] | null;
            thisWeekEvents: components["schemas"]["EventSummary"][];
            nextEvent?: components["schemas"]["EventSummary"] | null;
            recentActivity: components["schemas"]["LedgerSummary"][];
            communityExpenses: components["schemas"]["ExpenseSummary"][];
        };
        AnnouncementSummary: {
            /** Format: guid */
            id: string;
            title: string;
            body: string;
            category: string;
            /** Format: date-time */
            publishedAt: string;
            authorName: string;
        };
        EventSummary: {
            /** Format: guid */
            id: string;
            title: string;
            /** Format: date-time */
            eventDate: string;
            location?: string | null;
            category: string;
            rsvpEnabled: boolean;
        };
        LedgerSummary: {
            /** Format: guid */
            id: string;
            /** Format: date */
            entryDate: string;
            description: string;
            /** Format: decimal */
            chargeAmount: number;
            /** Format: decimal */
            paymentAmount: number;
            /** Format: decimal */
            runningBalance: number;
            entryType: string;
        };
        ExpenseSummary: {
            /** Format: guid */
            id: string;
            label: string;
            color: string;
            /** Format: decimal */
            amount: number;
        };
        ViolationListResponse: {
            items: components["schemas"]["ViolationDto"][];
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        ViolationDto: {
            /** Format: guid */
            id: string;
            title: string;
            description?: string | null;
            category: string;
            status: string;
            /** Format: date */
            issuedDate: string;
            /** Format: date */
            resolvedDate?: string | null;
            /** Format: date */
            dueDate?: string | null;
            /** Format: decimal */
            fineAmount?: number | null;
            imageUrl?: string | null;
        };
        ViolationListRequest: Record<string, never>;
        PollDto: {
            /** Format: guid */
            id: string;
            question: string;
            closingLabel: string;
            /** Format: int32 */
            totalVotes: number;
            options: components["schemas"]["PollOptionDto"][];
        };
        PollOptionDto: {
            /** Format: int32 */
            optionIndex: number;
            optionText: string;
            /** Format: int32 */
            voteCount: number;
            /** Format: decimal */
            percentage: number;
        };
        PollVoteRequest: {
            /** Format: int32 */
            optionIndex: number;
        };
        EventRsvpRequest: {
            attending: boolean;
        };
        EventListResponse: {
            items: components["schemas"]["EventDto"][];
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        EventDto: {
            /** Format: guid */
            id: string;
            title: string;
            description?: string | null;
            /** Format: date-time */
            eventDate: string;
            location?: string | null;
            category: string;
            rsvpEnabled: boolean;
            /** Format: int32 */
            rsvpCount: number;
        };
        EventListRequest: Record<string, never>;
        DocumentDownloadResponse: {
            url: string;
            /** Format: date-time */
            expiresAt: string;
        };
        DocumentListResponse: {
            items: components["schemas"]["DocumentDto"][];
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        DocumentDto: {
            /** Format: guid */
            id: string;
            name: string;
            category: string;
            /** Format: date */
            effectiveDate: string;
            fileSizeLabel: string;
            pinned: boolean;
        };
        DocumentListRequest: Record<string, never>;
        CommunityDirectoryResponse: {
            neighbors: components["schemas"]["NeighborDto"][];
            /** Format: int32 */
            totalSharing: number;
            /** Format: int32 */
            totalHouseholds: number;
        };
        NeighborDto: {
            address: string;
            name?: string | null;
            email?: string | null;
            phone?: string | null;
        };
        AnnouncementDto: {
            /** Format: guid */
            id: string;
            title: string;
            body: string;
            category: string;
            /** Format: date-time */
            publishedAt: string;
            pinned: boolean;
            /** Format: int32 */
            likeCount: number;
            /** Format: int32 */
            commentCount: number;
            authorName: string;
            authorRole?: string | null;
            imageUrl?: string | null;
        };
        AnnouncementListResponse: {
            items: components["schemas"]["AnnouncementDto"][];
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        AnnouncementListRequest: Record<string, never>;
        AuthResponse: {
            token: string;
            refreshToken: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["CurrentUserDto"];
        };
        CurrentUserDto: {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            initials: string;
            properties: components["schemas"]["PropertySummaryDto"][];
        };
        PropertySummaryDto: {
            /** Format: guid */
            id: string;
            accountNumber: string;
            address: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            accountNumber: string;
        };
        SwitchPropertyRequest: {
            /** Format: guid */
            propertyId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetAddressHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressHistoryDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatchDirectoryField: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectoryFieldPatchRequest2"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryFieldDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetDirectoryFields: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryFieldDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatchOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerPatchRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetProperty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetDrafts: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetLedger: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                startDate?: string | null;
                endDate?: string | null;
                type?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    StripeWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetStatement: {
        parameters: {
            query?: {
                startDate?: string | null;
                endDate?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetUnpaidAssessments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnpaidAssessmentsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpsertRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringPaymentRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringPaymentDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CancelRecurring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreateSetupIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupIntentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConfirmOneTimePayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPaymentRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmPaymentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreatePaymentIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIntentRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateIntentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetPaymentOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOptionsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetPaymentTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReconcilePayments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileResponse"];
                };
            };
        };
    };
    RunRecurringDrafts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDraftsResponse"];
                };
            };
        };
    };
    GetAlertPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPreferencesDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateAlertPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAlertPreferencesRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPreferencesDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    IngestBrowserTelemetry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetViolations: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: string | null;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViolationListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetPoll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VotePoll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PollVoteRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    RsvpEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRsvpRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetEvents: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                startDate?: string | null;
                endDate?: string | null;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetDocumentDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDownloadResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetDocuments: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                category?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetCommunityDirectory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityDirectoryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAnnouncements: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                category?: string | null;
                pinned?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RefreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    SwitchProperty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchPropertyRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
