// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HOAManagementCompany.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250728234626_Violation")]
    partial class Violation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HOAManagementCompany.Models.Violation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OccurrenceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("HOAManagementCompany.Models.ViolationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CovenantText")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ViolationTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5a56c9b-a14f-4f9b-afc1-82d00663aa01"),
                            CovenantText = "Owners must maintain lawn (placeholder)...",
                            Name = "GRASS"
                        },
                        new
                        {
                            Id = new Guid("3f843e9d-3e26-4696-84d6-f20f2dc20b1f"),
                            CovenantText = "Owners must maintain exterior (placeholder)...",
                            Name = "POWERWASH"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
